### ISSUE TITLE
icon add

### ISSUE THREAD

**Issue by BlueFireRO** [SanityZeroPercent/samp-discord-plugin#2]
![logo (1) (1)](https://github.com/SanityZeroPercent/samp-discord-plugin/assets/64308848/e2096993-3851-480d-adc1-d8e46002a569)
rpg.ultrakill.ro , rpg.ultrakill.ro:7777 or 5.183.171.192:7777 ,all work

**Comment by SanityZeroPercent** [comment]
Done!
