### ISSUE TITLE
...

### ISSUE THREAD

**Issue by iMarkeh18** [SanityZeroPercent/samp-discord-plugin#3]
samp.phr-rp.net:7777

![PHR-RP](https://github.com/SanityZeroPercent/samp-discord-plugin/assets/114968882/5bee8ea0-fc14-4d97-9116-0fd0e1724c5a)

**Comment by iMarkeh18** [comment]
@SanityZeroPercent THANKYOUUUUU!!!

**Comment by SanityZeroPercent** [comment]
done!
